packages:
  - "."
  - "layout-wasm"

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true

strictPeerDependencies: false
shamefullyHoist: true
nodeLinker: hoisted

ignore-workspace-root-check: true
