packages:
  - '.'
  - 'layout-wasm'

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  wasm-pack: true

strictPeerDependencies: false
